[alias]
rel = "build --release"
#rel = "build --release --example kaonic-tcp-mesh --example tcp-client --example kaonic-client --example kaonic-mesh --example link-client --example tcp-server --example testnet-client"
inst = "install --path ."
clip = "clippy --release"
pub = "publish"
up = "update --verbose"

[build]
target = "x86_64-unknown-linux-musl"

[install]
target = "x86_64-unknown-linux-musl"

[publish]
target = "x86_64-unknown-linux-musl"

[clippy]
target = "x86_64-unknown-linux-musl"

[update]
target = "x86_64-unknown-linux-musl"
